# Build settings
[build]
  publish = "dist"

# Redirects (optional, if you're using an external CDN or image service)
[[redirects]]
  from = "/images/*"
  to = "https://res.cloudinary.com/your-cloud-name/image/upload/w_800,h_600,c_fill,q_auto,f_auto:/images/:splat"
  status = 301

# Cache headers for images
[[headers]]
for = "/*.jpg"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.jpeg"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.png"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.webp"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.svg"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# Optionally, add a default redirect for all assets (if needed)
[[headers]]
for = "/*"
[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"
